utb_eshop_patek/utb_eshop_patek/Areas/Admin/Controllers/ProductsController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using utb_eshop_patek.Application.Admin.ApplicationServices.Products;
using utb_eshop_patek.Application.Admin.ViewModels.Products;
using utb_eshop_patek.Application.Client.ViewModels.Ratings;
using utb_eshop_patek.Application.Client.ApplicationServices.Ratings;
using utb_eshop_patek.Areas.Admin.Controllers.Common;

namespace utb_eshop_patek.Areas.Admin.Controllers
{
    public class ProductsController : AdminController
    {
        private readonly IProductApplicationService _productApplicationService;
        private readonly IRatingApplicationService _ratingApplicationService;

        public ProductsController(IProductApplicationService productApplicationService,
            IRatingApplicationService ratingApplicationService)
        {
            _productApplicationService = productApplicationService;
            _ratingApplicationService = ratingApplicationService;
        }

        public IActionResult Index()
        {
            var vm = _productApplicationService.GetIndexViewModel();
            return View(vm);
        }

        public IActionResult Ratings(int id)
        {
            var product = _productApplicationService.GetProductViewModel(id);
            return View(product);
        }

        public void EnableRatings(int productID,bool value)
        {
            _productApplicationService.EnableProductRatings(productID, value);
        }

        public void DeleteRating(int id,bool value)
        {
            _ratingApplicationService.DeleteRating(id,value);
        }

        public IActionResult Edit(int id)
        {
            var product = _productApplicationService.GetProductViewModel(id);
            return View(product);
        }
        
        [HttpPost]
        public IActionResult Edit(ProductViewModel model)
        {
            var product = _productApplicationService.Update(model);
            return Json(product);
        }

        public IActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Insert(ProductViewModel model)
        {
            var product = _productApplicationService.Insert(model);
            return Json(product);
        }

        public IActionResult Delete(ProductViewModel model)
        {
            _productApplicationService.Delete(model);
            return RedirectToAction(nameof(Index));
        }
    }
}

utb_eshop_patek/utb_eshop_patek/Areas/Client/Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using utb_eshop_patek.Application.Admin.ApplicationServices.Security;
using utb_eshop_patek.Application.Client.ApplicationServices.Carts;
using utb_eshop_patek.Domain.Constants;

namespace utb_eshop_patek.Areas.Client.Controllers
{
    [Area("Client")]
    public class CartsController : Controller
    {
        private readonly ICartApplicationService _cartApplicationService;
        private readonly ISecurityApplicationService _securityApplicationService;

        public CartsController(
            ICartApplicationService cartApplicationService,
            ISecurityApplicationService securityApplicationService
            )
        {
            _cartApplicationService = cartApplicationService;
            _securityApplicationService = securityApplicationService;
        }

        public async Task<IActionResult> Index()
        {
            var vm = _cartApplicationService.GetIndexViewModel(GetTrackingCode());

            var user = await _securityApplicationService.GetCurrentUser(User);
            vm.UserID = user?.Id;
            vm.Login = user?.Email;

            return View(vm);
        }

        [HttpPost]
        public JsonResult AddToCart(int id, int amount)
        {
            var cartItem = _cartApplicationService.AddToCart(id, amount, GetTrackingCode());
            return Json(cartItem);
        }

        [HttpPost]
        public JsonResult RemoveFromCart(int id)
        {
            _cartApplicationService.RemoveFromCart(id, GetTrackingCode());
            return Json("success");
        }

        private string GetTrackingCode()
        {
            var utc = Request.Cookies[Cookies.UserTrackingCode];
            if (utc != null)
                return utc;

            var guid = Guid.NewGuid().ToString();
            var options = new CookieOptions();
            options.Expires = DateTime.Now.AddYears(1);

            Response.Cookies.Append(Cookies.UserTrackingCode, guid, options);
            return guid;
        }
    }
}

utb_eshop_patek/utb_eshop_patek/Areas/Client/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using utb_eshop_patek.Application.Admin.ApplicationServices.Products;
using utb_eshop_patek.Application.Admin.ApplicationServices.Security;
using utb_eshop_patek.Application.Client.ApplicationServices.Ratings;

namespace utb_eshop_patek.Areas.Client.Controllers
{
    [Area("Client")]
    public class ProductsController : Controller
    {
        private readonly IProductApplicationService _productApplicationService;
        private readonly ISecurityApplicationService _securityApplicationService;

        public ProductsController(
            IProductApplicationService productApplicationService,
            ISecurityApplicationService securityApplicationService
            )
        {
            _productApplicationService = productApplicationService;
            _securityApplicationService = securityApplicationService;
        }

        public async Task<IActionResult> Index()
        {
            var vm = _productApplicationService.GetIndexViewModel();

            var user = await _securityApplicationService.GetCurrentUser(User);
            vm.UserID = user?.Id;
            vm.Login = user?.Email;

            return View(vm);
        }
        public async Task<IActionResult> Detail(int id)
        {
            var vm = _productApplicationService.GetProductViewModel(id);

            var user = await _securityApplicationService.GetCurrentUser(User);
            vm.UserID = user?.Id;
            vm.Login = user?.Email;

            return View(vm);
        }
    }
}

utb_eshop_patek/utb_eshop_patek/Areas/Client/Controllers/RatingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using utb_eshop_patek.Application.Admin.ApplicationServices.Products;
using utb_eshop_patek.Application.Admin.ApplicationServices.Security;
using utb_eshop_patek.Application.Client.ApplicationServices.Ratings;
using utb_eshop_patek.Domain.Constants;

namespace utb_eshop_patek.Areas.Client.Controllers
{
    [Area("Client")]
    public class RatingsController : Controller
    {
        private readonly IRatingApplicationService _ratingApplicationService;
        private readonly ISecurityApplicationService _securityApplicationService;
        private readonly IProductApplicationService _productApplicationService;

        public RatingsController(IRatingApplicationService ratingApplicationService, 
            ISecurityApplicationService securityApplicationService, 
            IProductApplicationService productApplicationService)
        {
            _ratingApplicationService = ratingApplicationService;
            _securityApplicationService = securityApplicationService;
            _productApplicationService = productApplicationService;
        }

        public async Task<IActionResult> Index(int id, string name)
        {          
            var user = await _securityApplicationService.GetCurrentUser(User);

            if (user != null)
            {
                var vmEmpty = _ratingApplicationService.GetEmptyViewModel(id, name);
                vmEmpty.UserID = user?.Id;
                vmEmpty.Login = user?.Email;
                return View(vmEmpty);
            }

            return RedirectToAction("Detail", "Products", new { area = "Client" , id });
        }

        [HttpPost]
        public async Task AddRating(int id, string comment, int rateValue)
        {
            var user = await _securityApplicationService.GetCurrentUser(User);
            var username = user.Email;
            _ratingApplicationService.AddRating(id, comment, rateValue, username);
        }
    }
}

utb_eshop_patek/utb_eshop_patek/Areas/Client/Views/Products/Detail.cshtml
@model utb_eshop_patek.Application.Admin.ViewModels.Products.ProductViewModel

@{
    ViewData["Title"] = "Detail";
}

<!-- Font Awesome Icon Library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>

    /* use display:inline-flex to prevent whitespace issues. alternatively, you can put all the children of .rating-group on a single line */
    .rating-group {
        display: inline-flex;
    }

    /* make hover effect work properly in IE */
    .rating__icon {
        pointer-events: none;
    }

    /* hide radio inputs */
    .rating__input {
        position: absolute !important;
        left: -9999px !important;
    }

    /* set icon padding and size */
    .rating__label {
        cursor: pointer;
        padding: 0 0.1em;
        font-size: 2rem;
    }

    /* set default star color */
    .rating__icon--star {
        color: orange;
    }

    /* set color of none icon when unchecked */
    .rating__icon--none {
        color: #eee;
    }

    /* if none icon is checked, make it red */
    .rating__input--none:checked + .rating__label .rating__icon--none {
        color: red;
    }

    /* if any input is checked, make its following siblings grey */
    .rating__input:checked ~ .rating__label .rating__icon--star {
        color: #ddd;
    }
</style>



<h2>Detail</h2>

<div>
    <div class="row">
        <div class="col-md-1">
            <h4>@Model.Name</h4>
        </div>
        <div class="col-md-2" id="full-stars-example">
            <div class="rating-group">
                <input class="rating__input rating__input--none" name="rating" id="rating-none" value="0" type="radio" disabled>
                <label aria-label="No rating" class="rating__label" for="rating-none"><i class="rating__icon rating__icon--none fa fa-ban"></i></label>
                <label aria-label="1 star" class="rating__label" for="rating-1"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="rating" id="rating-1" value="1" type="radio" disabled>
                <label aria-label="2 stars" class="rating__label" for="rating-2"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="rating" id="rating-2" value="2" type="radio" disabled>
                <label aria-label="3 stars" class="rating__label" for="rating-3"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="rating" id="rating-3" value="3" type="radio" disabled>
                <label aria-label="4 stars" class="rating__label" for="rating-4"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="rating" id="rating-4" value="4" type="radio" disabled>
                <label aria-label="5 stars" class="rating__label" for="rating-5"><i class="rating__icon rating__icon--star fa fa-star"></i></label>
                <input class="rating__input" name="rating" id="rating-5" value="5" type="radio" disabled>
            </div>
        </div>
        @if (Model.EnableRatings == true)
        {
            if (Model.Login != null)
            {
                <div class="col-md-9">
                    <a id="rate" class="btn btn-primary" data-name="@Model.Name" asp-controller="Ratings" asp-action="Index" asp-route-id="@Model.ID" asp-route-name="@Model.Name">Ohodnotit</a>
                </div>
            }
            else
            {
                <div class="col-md-9">
                    <button class="btn btn-primary" disabled>Pro přidání hodnocení je potřeba se přihlásit</button>
                </div>
            }

        }
        else
        {
            <div class="col-md-9">
                <button class="btn btn-primary" disabled>K tomuto produktu nelze přidávat hodnocení</button>
            </div>
        }

    </div>
    <hr />
    <div class="row">
        <div class="col-md-5">
            <img src="@Model.ImageURL" alt="@Model.Name" style="max-height:200px;" />
        </div>
        <div class="col-md-3">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Price)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Price)
                </dd>
            </dl>
        </div>
        <div class="col-md-2">
            <input class="form-control" type="number" value="1" />
            <button id="add-to-cart" data-id="@Model.ID" class="btn btn-primary">Přidat do košíku</button>

            <div class="alert alert-success" id="success-alert" style="display:none;">
                <button type="button" class="close" data-dismiss="alert">x</button>
                <strong>Added!</strong>
            </div>
        </div>
    </div>
</div>
<hr />
@if (Model.EnableRatings == true)
{
    <h3>Hodnocení produktu:</h3>
    <div>

        @foreach (var rating in Model.ratings)
        {
            if(rating.IsDeleted==false){
                <div class="col-sm-4">
                    <dl class="dl-horizontal">
                        <dt>
                            Uživatel:
                        </dt>
                        <dd>
                            @rating.UserName
                        </dd>
                        <dt>
                            Hodnocení:
                        </dt>
                        <dd>
                            @rating.Comment
                        </dd>
                        <dt>
                            Počet Hvězdiček:
                        </dt>
                        <dd>
                            @rating.RatingValue
                        </dd>
                    </dl>
                </div>
            }
        }


    </div>
}
<div class="row"></div>



@section scripts{
    <script>
    $(document).ready(() => {
        $('#add-to-cart').click(addToCart);
        var stars = $("input[value='@Model.ratingRatio']");
        stars.attr('checked', 'checked');
    });

    function addToCart() {
        var id = $(this).data('id');
        var amount = $(this).closest('div').find('input').val();

        $.ajax({
            method: 'POST',
            url: '@Url.Action("AddToCart", "Carts")',
            data: {id: id, amount: amount},
            success: function () {
                $("#success-alert").fadeTo(2000, 500).slideUp(500, function(){
                    $("#success-alert").slideUp(500);
                });
            }
        })
        }
    </script>
}

utb_eshop_patek/utb_eshop_patek/Areas/Client/Views/Products/Index.cshtml
@model IndexViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<div class="row">
    @foreach (var product in Model.Products)
    {
        <div class="col-xs-4">
            <div class="thumbnail">
                <img class="product-image" src="@product.ImageURL" alt="@product.Name" />
                <div class="caption">
                    <h3>@product.Name</h3>
                    <a class="btn btn-primary" asp-action="Detail" asp-route-id="@product.ID">Detail</a>
                </div>
            </div>
        </div>
    }
</div>